version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segment]]	
    type = "path"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#61AFEF"




